services:
  - type: web
    name: multiverse-arena-server
    plan: free
    buildCommand: npm ci && npm -w server run build
    startCommand: npm -w server run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
    runtime: node

  - type: static
    name: multiverse-arena-client
    buildCommand: npm ci && npm -w client run build
    staticPublishPath: client/dist
    autoDeploy: true
    envVars:
      - key: VITE_SERVER_URL
        value: https://multiverse-arena-server.onrender.com
